blogs/urls.py
# @Time    : 18-6-5 下午2:19
# @Author  : zhangyanna
# @Site    : 
# @File    : urls.py
# @Software: PyCharm

from django.conf.urls import url
from .views import index,list,base,search,show

urlpatterns = [
    url(r'^index/$', index, name='index'),
    url(r'^list/$',list,name='list'),
    url(r'^base/$',base,name='base'),
    url(r'^search/$',search.as_view() , name='search'),
    url(r'^tags/(?P<tid>[0-9]+)/$', list, name='tags'),
    url(r'^category/(?P<cid>[0-9]+)/$', list,name='category'),
    url(r'^xiangqing/(?P<sh>[0-9]+)/$', show, name='show_x'),
    url(r'^show/$',show,name='show'),



]

django_blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blogs import urls as blog_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include(blog_urls, namespace='blog'))

]

blogs/models.py
from django.db import models
from users.models import BlogUser
from datetime import datetime


class Banner(models.Model):
    title = models.CharField(verbose_name='标题', max_length=50)
    cover = models.ImageField(verbose_name='轮播图', upload_to='static/images/banner')
    link_url = models.URLField(max_length=150, verbose_name='图片链接')
    idx = models.IntegerField(verbose_name='索引')
    is_active = models.BooleanField(verbose_name='是否激活', default=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '轮播图'
        verbose_name_plural = verbose_name


class BlogCategory(models.Model):
    name = models.CharField(max_length=30, verbose_name='分类名称', default='')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '博客分类'
        verbose_name_plural = verbose_name


class Tags(models.Model):
    name = models.CharField(verbose_name='标签', max_length=30)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name


class Post(models.Model):
    user = models.ForeignKey(BlogUser, verbose_name='作者')
    category = models.ForeignKey(BlogCategory, verbose_name='博客分类', default=None)
    tags = models.ManyToManyField(Tags, verbose_name='标签')
    title = models.CharField(verbose_name='标题', max_length=30, null=False)
    content = models.CharField(verbose_name='内容', max_length=4000, null=False)
    pub_date = models.DateTimeField(verbose_name='发布时间', default=datetime.now)
    cover = models.ImageField(verbose_name='博客封面', upload_to='static/image/post', default=None)
    views = models.IntegerField(verbose_name='浏览量')
    is_recomment = models.BooleanField(verbose_name='是否推荐博客', default=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '博客'
        verbose_name_plural = verbose_name


class Comment(models.Model):
    user = models.ForeignKey(BlogUser, verbose_name='评论者')
    post = models.ForeignKey(Post, verbose_name='博客')
    content = models.CharField(verbose_name='评论内容', max_length=400)
    pub_date = models.DateTimeField(verbose_name='发布时间', default=datetime.now)

    def __str__(self):
        return self.post.title

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name


class FriendlyLink(models.Model):
    title = models.CharField(max_length=30, verbose_name='友情链接标题')
    link = models.URLField(max_length=150, verbose_name='链接地址', default=None)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '友情链接'
        verbose_name_plural = verbose_name

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import datetime


# Create your models here.
class BlogUser(AbstractUser):
    nikename = models.CharField(max_length=30, default='', verbose_name='昵称')


class EmailVerifyRecord(models.Model):
    code = models.CharField(max_length=50, verbose_name='验证码', default='')
    eamil = models.CharField(max_length=30, verbose_name='邮箱')
    send_type = models.CharField(max_length=30, verbose_name='验证码类型',
                                 choices=(('register', '注册'), ('forget', '找回密码'), ('update_email', '修改邮箱')))
    send_time = models.DateTimeField(verbose_name='发送时间', default=datetime.now)

    class Meta:
        verbose_name = '邮箱验证码'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.eamil

blogs/views.py
from django.shortcuts import render
from .models import Banner,Post,Comment,BlogCategory,FriendlyLink,Tags
from django.views.generic.base import View
from django.db.models import Q
from pure_pagination import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse

#搜索框
class search(View):

    def post(self,request):
        # 获取搜索框输入的内容
        kw=request.POST.get('keyword')
        # 匹配博客的标题或者内容
        post_list=Post.objects.filter(Q(title__contains=kw) | Q(content__contains=kw))


        ctx={
            'post_list':post_list,

        }

        return render(request,'list.html',ctx)

def index(request):
    # 轮播图
    banner_list = Banner.objects.all()
    # 推介博客
    recomment_list=Post.objects.filter(is_recomment=True)
    for recomment in recomment_list:
        recomment.content=recomment.content[:70]+'....'
    # 最新发布
    post_list=Post.objects.all().order_by('-pub_date')
    for count in post_list:
        count.content=count.content[:100]+'......'
    #博客分类
    BlogCategory_list=BlogCategory.objects.all()

    #最新评论
    comment_list = Comment.objects.order_by('-pub_date')
    new_commit_list = []
    for commit in comment_list:
        if commit.post not in new_commit_list:
            new_commit_list.append(commit.post)

    #友情链接
    FriendlyLink_list=FriendlyLink.objects.all()

    #分页
    try:
        page = request.GET.get('page', 1)
    except PageNotAnInteger:
        page = 1

    p = Paginator(post_list, per_page=1, request=request)
    post_list = p.page(page)

    ctx = {
        'banner_list':banner_list,
        'recomment_list':recomment_list,
        'post_list':post_list,
        'BlogCategory_list':BlogCategory_list,
        'new_commit_list':new_commit_list,
        'FriendlyLink_list':FriendlyLink_list,
    }
    return render(request, 'index.html', ctx)



def list(request,tid=-1,cid=-1):
    #点击标签获取博客
    if tid!=-1:
        cat=Tags.objects.get(id=tid)
        post_list = cat.post_set.all()
    #用分类查询博客
    elif cid != -1:
        cat = BlogCategory.objects.get(id=cid)
        post_list = cat.post_set.all()
    else:
        post_list=Post.objects.order_by('-pub_date')

    #标签云----------------------------------
    tags = Tags.objects.all()
    #取出所有标签放入一个列表中
    tag_message_list = []
    for t in tags:
        count = len(t.post_set.all())
        tag_message_list.append({'name':t.name,'id':t.id,'count':count})


    ctx={
            'post_list': post_list,
            'tag_message_list': tag_message_list,
        }

    return render(request,'list.html',ctx)

def base(request):
    return render(request, 'base.html')

#详情页
def show(request,sh=-1):
    cht = int(sh)
    if cht != -1:
        post_list = Post.objects.get(id=cht)
    else:
        post_list = Post.objects.filter(is_recomment=True).order_by('-views')
        post_list = post_list[0]
    #最新评论 去重
    comment_list = Comment.objects.order_by('-pub_date')
    new_comment_list = []
    for test in comment_list:
        if test.post not in new_comment_list:
            new_comment_list.append(test.post)
    #标签
    tag_list = post_list.tags.all()

    #相关推介
    tuijie=post_list.category
    tuijie_list=Post.objects.filter(category=tuijie)

    ctx = {
        'post': post_list,
        'new_comment_list':new_comment_list,
        'tuijie_list':tuijie_list,
        'tag_list': tag_list,

    }

    return render(request, 'show.html', ctx)

users/views.py
from django.shortcuts import render

# Create your views here.

templates/_pagination.html
{% load i18n %}
<div class="pagination">
    {% if post_list.has_previous %}
        <a href="?{{ post_list.previous_page_number.querystring }}" class="prev">&lsaquo;&lsaquo; 上一页</a>
    {% else %}
        <span class="disabled prev">&lsaquo;&lsaquo; 上一页</span>
    {% endif %}
    {% for page in post_list.pages %}
        {% if page %}
            {% ifequal page post_list.number %}
                <span class="current page">{{ page }}</span>
            {% else %}
                <a href="?{{ page.querystring }}" class="page">{{ page }}</a>
            {% endifequal %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
    {% if post_list.has_next %}
        <a href="?{{ post_list.next_page_number.querystring }}" class="next">下一页 &rsaquo;&rsaquo;</a>
    {% else %}
        <span class="disabled next">下一页 &rsaquo;&rsaquo;</span>
    {% endif %}
</div>

templates/base.html
{% load static %}
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>知奇博客首页</title>
    <meta name="keywords" content="">
    <meta name="description" content="">

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/nprogress.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="apple-touch-icon-precomposed" href="{% static 'images/icon.png' %}/static/images/icon.png">
    <link rel="shortcut icon" href="">

    <script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
    <script src="{% static 'js/nprogress.js' %}"></script>
    <script src="{% static 'js/jquery.lazyload.min.js' %}"></script>

</head>
<body class="user-select">
<header class="header">
    <nav class="navbar navbar-default" id="navbar">
        <div class="container">
            <div class="header-topbar hidden-xs link-border">
                <ul class="site-nav topmenu">
                    <li><a href="#">标签云</a></li>
                    <li><a href="#" rel="nofollow">读者墙</a></li>
                    <li><a href="#" title="RSS订阅">
                        <i class="fa fa-rss">
                        </i> RSS订阅
                    </a></li>
                </ul>
                爱学习 更爱分享
            </div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#header-navbar" aria-expanded="false"><span class="sr-only"></span> <span
                        class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span></button>
                <h1 class="logo hvr-bounce-in"><a href="#" title="知奇课堂博客"><img
                        src="/static/images/201610171329086541.png"
                        alt="知奇课堂博客"></a></h1>
            </div>
            <div class="collapse navbar-collapse" id="header-navbar">
                <form class="navbar-form visible-xs" action="/Search" method="post">
                    <div class="input-group">
                        <input type="text" name="keyword" class="form-control" placeholder="请输入关键字" maxlength="20"
                               autocomplete="off">
                        <span class="input-group-btn">
		<button class="btn btn-default btn-search" name="search" type="submit">搜索</button>
		</span></div>
                </form>

                <ul class="nav navbar-nav navbar-left">
                    <li><a data-cont="知奇课堂博客" title="知奇课堂博客" href="{% url 'blog:index' %}">首页</a></li>
                    <li><a data-cont="列表页" title="列表页" href="{% url 'blog:list' %}">列表页</a></li>
                    <li><a data-cont="详细页" title="详细页" href="{% url 'blog:show' %}">详细页</a></li>
{#                    <li><a data-cont="404" title="404" href="404.html">404</a></li>#}
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li><a data-cont="登录" title="登录" href="#">登录</a></li>
                    <li><a data-cont="注册" title="注册" href="#">注册</a></li>
                </ul>

            </div>
        </div>
    </nav>
</header>

<section class="container">
    {% block a %}

    {% endblock  %}
</section>
<footer class="footer">
    <div class="container">
        <p>Copyright &copy; 2016.Company name All rights reserved.</p>
    </div>
    <div id="gotop"><a class="gotop"></a></div>
</footer>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{#<script src="{% static 'js/jquery.ias.js' %}"></script>#}
<script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block a %}
<section class="container">
    <div class="content-wrap">
        <div class="content">
            <!-- banner 开始 -->
            <div id="focusslide" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">

                    {% for banner in banner_list %}
                        {% if banner.is_active %}
                            <li data-target="#focusslide" data-slide-to="{{ banner.idx }}" class="active"></li>
                        {% else %}
                            <li data-target="#focusslide" data-slide-to="{{ banner.idx }}"></li>
                        {% endif %}
                    {% endfor %}

                </ol>
                <div class="carousel-inner" role="listbox">

                    {% for banner in banner_list %}
                        {% if banner.is_active %}
                            <div class="item active">
                                <a href="{{ banner.link_url }}" target="_blank" title="{{ banner.title }}">
                                    <img src="/{{ banner.cover }}" alt="{{ banner.title }}" class="img-responsive"></a>
                            </div>
                        {% else %}
                            <div class="item">
                                <a href="{{ banner.link_url }}" target="_blank" title="{{ banner.title }}">
                                    <img src="/{{ banner.cover }}" alt="{{ banner.title }}" class="img-responsive"></a>
                            </div>
                        {% endif %}
                    {% endfor %}

                </div>
                <a class="left carousel-control" href="#focusslide" role="button" data-slide="prev" rel="nofollow">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">上一个</span> </a>
                <a class="right carousel-control" href="#focusslide" role="button" data-slide="next" rel="nofollow">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">下一个</span> </a>
            </div>

            <!-- banner 结束 -->

            {#     推介博客       #}
            {% for recomment_list in recomment_list%}

                <article class="excerpt-minic excerpt-minic-index">
                    <h2><span class="red">【推荐】</span><a target="_blank" href="{% url 'blog:show_x' recomment_list.id %}" title={{ recomment_list.title }}>{{recomment_list.title }}</a>
                    </h2>
                    <p class="note">{{ recomment_list.content }}</p>
                </article>
            {% endfor %}
            {# 推介博客结束           #}

            {#   博客分类     #}
            <div class="title">
                <h3>最新发布</h3>
                <div class="more">
                    {% for BlogCategory_list in BlogCategory_list %}
                    <a href="{% url 'blog:category' BlogCategory_list.id %}" title={{ BlogCategory_list.name }}>{{ BlogCategory_list.name }}</a>

                    {% endfor %}
                </div>
            </div>
            {#     博客分类结束   #}

            {# 最新发布       #}
            {% for post in post_list.object_list %}
                <article class="excerpt excerpt-1" style="">
                <a class="focus" href="{% url 'blog:show_x' post.id %}" title="{{ post.title }}" target="_blank"><img class="thumb"
                                                                                       data-original="/{{ post.cover }}"
                                                                                       src="/{{ post.cover }}"
                                                                                       alt="{{ post.title }}"
                                                                                       style="display: inline;"></a>
                <header><a class="cat" href="{% url 'blog:show_x' post.id %}" title="知奇课堂-博客">知奇课堂-博客<i></i></a>
                    <h2><a href="{% url 'blog:show_x' post.id %}" title="{{ post.title }}" target="_blank">{{ post.title }}</a>
                    </h2>
                </header>
                <p class="meta">
                    <time class="time"><i class="glyphicon glyphicon-time"></i> {{ post.pub_date  }}</time>
                    <span class="views"><i class="glyphicon glyphicon-eye-open"></i>{{ post.views }}</span> <a class="comment"
                                                                                                   href="##comment"
                                                                                                   title="评论"
                                                                                                   target="_blank"><i
                        class="glyphicon glyphicon-comment"></i>{{ post.comment_set.count }}</a>
                </p>
                <p class="note">{{ post.content }}</p>
            </article>

            {% endfor %}
            {% include '_pagination.html' %}
        {# 最新发布结束       #}


            <nav class="pagination" style="display: none;">
                <ul>
                    <li class="prev-page"></li>
                    <li class="active"><span>1</span></li>
                    <li><a href="?page=2">2</a></li>
                    <li class="next-page"><a href="?page=2">下一页</a></li>
                    <li><span>共 2 页</span></li>
                </ul>
            </nav>
        </div>
    </div>
    <aside class="sidebar">
        <div class="fixed">
            <div class="widget widget-tabs">
                <ul class="nav nav-tabs" role="tablist">
                    <li role="presentation" class="active"><a href="#notice" aria-controls="notice" role="tab"
                                                              data-toggle="tab">统计信息</a></li>
                    <li role="presentation"><a href="#contact" aria-controls="contact" role="tab"
                                               data-toggle="tab">联系站长</a></li>
                </ul>
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane contact active" id="notice">
                        <h2>日志总数:
                            888篇
                        </h2>
                        <h2>网站运行:
                            <span id="sitetime">88天 </span></h2>
                    </div>
                    <div role="tabpanel" class="tab-pane contact" id="contact">
                        <h2>QQ:
                            <a href="" target="_blank" rel="nofollow" data-toggle="tooltip" data-placement="bottom"
                               title="" data-original-title="QQ:"></a>
                        </h2>
                        <h2>Email:
                            <a href="#" target="_blank" data-toggle="tooltip" rel="nofollow" data-placement="bottom"
                               title="" data-original-title="#"></a></h2>
                    </div>
                </div>
            </div>
            {#  搜索框开始  --------------------------        #}
            {% include 'search.html' %}

{#            <div class="widget widget_search">#}
{#                <form class="navbar-form" action="{% url 'blog:list' %}" method="post">#}
{#                    {% csrf_token %}#}
{#                    <div class="input-group">#}
{#                        <input type="text" name="keyword" class="form-control" size="35" placeholder="请输入关键字"#}
{#                               maxlength="15" autocomplete="off">#}
{#                        <span class="input-group-btn">#}
{#		<button class="btn btn-default btn-search" name="search" type="submit">搜索</button>#}
{#		</span></div>#}
{#                </form>#}
{#            </div>#}

            {#  搜索框结束          #}
        </div>
        <div class="widget widget_hot">
            <h3>最新评论文章</h3>
            {# 最新评论 ----------------------#}

            <ul>
                {% for post in new_commit_list %}
                <li><a title={{ post.title }} href="#"><span class="thumbnail">
				<img class="thumb" data-original="{{ post.cover }}"
                     src="{{ post.cover }}"
                     alt="{{ post.title }}" style="display: block;">
			</span><span class="text">{{ post.title }}</span><span class="muted"><i class="glyphicon glyphicon-time"></i>
				{{ post.pub_date }}
			</span><span class="muted"><i class="glyphicon glyphicon-eye-open"></i>{{ post.views }}</span></a></li>
                {% endfor %}

            </ul>
        </div>
        {#最新评论结束---------------------------#}

        <div class="widget widget_sentence">
            <h3>友情链接</h3>
            <div class="widget-sentence-link">
                {% for i in FriendlyLink_list %}
                    <a href="#" title={{ i.title }} target="_blank">{{ i.title }}</a>
                {% endfor %}
            </div>
        </div>

    </aside>
</section>
{% endblock a %}

templates/list.html
{% extends 'base.html' %}




{% block a %}
    <section class="container">
        <div class="content-wrap">
            <div class="content">
                <div class="title">
                    <h3 style="line-height: 1.3">博客列表</h3>
                </div>
               {% for post in post_list %}
                <article class="excerpt excerpt-1" style="">
                <a class="focus" href="#" title="{{ post.title }}" target="_blank"><img class="thumb"
                                                                                       data-original="/{{ post.cover }}"
                                                                                       src="/{{ post.cover }}"
                                                                                       alt="{{ post.title }}"
                                                                                       style="display: inline;"></a>
                <header><a class="cat" href="#" title="知奇课堂-博客">知奇课堂-博客<i></i></a>
                    <h2><a href="#" title="{{ post.title }}" target="_blank">{{ post.title }}</a>
                    </h2>
                </header>
                <p class="meta">
                    <time class="time"><i class="glyphicon glyphicon-time"></i> {{ post.pub_date  }}</time>
                    <span class="views"><i class="glyphicon glyphicon-eye-open"></i>{{ post.views }}</span> <a class="comment"
                                                                                                   href="##comment"
                                                                                                   title="评论"
                                                                                                   target="_blank"><i
                        class="glyphicon glyphicon-comment"></i>{{ post.comment_set.count }}</a>
                </p>
                <p class="note">{{ post.content }}</p>
            </article>

            {% endfor %}
{#            {% include '_pagination.html' %}#}



                <nav class="pagination" style="display: none;">
                    <ul>
                        <li class="prev-page"></li>
                        <li class="active"><span>1</span></li>
                        <li><a href="?page=2">2</a></li>
                        <li class="next-page"><a href="?page=2">下一页</a></li>
                        <li><span>共 2 页</span></li>
                    </ul>
                </nav>
            </div>
        </div>
        <aside class="sidebar">
            <div class="fixed">
            {#  搜索               #}
                {% include 'search.html' %}
            {# 搜索结束           #}
                <div class="widget widget_sentence">
                    <h3>标签云</h3>
                    <div class="widget-sentence-content">
                        <ul class="plinks ptags">

                            {% for tag_message in tag_message_list %}
                                <li><a href="{% url 'blog:tags' tag_message.id %}" title="{{ tag_message.name }}" draggable="false">{{ tag_message.name }}
                                    <span class="badge">{{ tag_message.count }}</span></a>
                                </li>
                            {% endfor a %}

{#                             {% for tag_message in tag_message_list %}#}
{#                                <li><a href="{% url 'blog:category' tag_message.id %}" title="{{ tag_message.name }}" draggable="false">{{ tag_message.name }}#}
{#                                    <span class="badge">{{ tag_message.count }}</span></a>#}
{#                                </li>#}
{#                            {% endfor a %}#}




                        </ul>
                    </div>
                </div>
            </div>
            <div class="widget widget_hot">
                <h3>最新评论文章</h3>
                <ul>

                    <li><a title="知奇课堂-Python开发课程" href="#"><span class="thumbnail">
<img class="thumb" data-original="images/201610181739277776.jpg" src="images/201610181739277776.jpg"
     alt="知奇课堂-Python开发课程" style="display: block;">
</span><span class="text">知奇课堂-Python开发课程</span><span class="muted"><i class="glyphicon glyphicon-time"></i>
2016-11-01
</span><span class="muted"><i class="glyphicon glyphicon-eye-open"></i>88</span></a></li>
                    <li><a title="知奇课堂-Python开发课程" href="#"><span class="thumbnail">
<img class="thumb" data-original="images/201610181739277776.jpg" src="images/201610181739277776.jpg"
     alt="知奇课堂-Python开发课程" style="display: block;">
</span><span class="text">知奇课堂-Python开发课程</span><span class="muted"><i class="glyphicon glyphicon-time"></i>
2016-11-01
</span><span class="muted"><i class="glyphicon glyphicon-eye-open"></i>88</span></a></li>
                    <li><a title="知奇课堂-Python开发课程" href="#"><span class="thumbnail">
<img class="thumb" data-original="images/201610181739277776.jpg" src="images/201610181739277776.jpg"
     alt="知奇课堂-Python开发课程" style="display: block;">
</span><span class="text">知奇课堂-Python开发课程</span><span class="muted"><i class="glyphicon glyphicon-time"></i>
2016-11-01
</span><span class="muted"><i class="glyphicon glyphicon-eye-open"></i>88</span></a></li>
                    <li><a title="知奇课堂-Python开发课程" href="#"><span class="thumbnail">
<img class="thumb" data-original="images/201610181739277776.jpg" src="images/201610181739277776.jpg"
     alt="知奇课堂-Python开发课程" style="display: block;">
</span><span class="text">知奇课堂-Python开发课程</span><span class="muted"><i class="glyphicon glyphicon-time"></i>
2016-11-01
</span><span class="muted"><i class="glyphicon glyphicon-eye-open"></i>88</span></a></li>
                    <li><a title="知奇课堂-Python开发课程" href="#"><span class="thumbnail">
<img class="thumb" data-original="images/201610181739277776.jpg" src="images/201610181739277776.jpg"
     alt="知奇课堂-Python开发课程" style="display: block;">
</span><span class="text">知奇课堂-Python开发课程</span><span class="muted"><i class="glyphicon glyphicon-time"></i>
2016-11-01
</span><span class="muted"><i class="glyphicon glyphicon-eye-open"></i>88</span></a></li>
                    <li><a title="知奇课堂-Python开发课程" href="#"><span class="thumbnail">
<img class="thumb" data-original="images/201610181739277776.jpg" src="images/201610181739277776.jpg"
     alt="知奇课堂-Python开发课程" style="display: block;">
</span><span class="text">知奇课堂-Python开发课程</span><span class="muted"><i class="glyphicon glyphicon-time"></i>
2016-11-01
</span><span class="muted"><i class="glyphicon glyphicon-eye-open"></i>88</span></a></li>
                    <li><a title="知奇课堂-Python开发课程" href="#"><span class="thumbnail">
<img class="thumb" data-original="images/201610181739277776.jpg" src="images/201610181739277776.jpg"
     alt="知奇课堂-Python开发课程" style="display: block;">
</span><span class="text">知奇课堂-Python开发课程</span><span class="muted"><i class="glyphicon glyphicon-time"></i>
2016-11-01
</span><span class="muted"><i class="glyphicon glyphicon-eye-open"></i>88</span></a></li>
                    <li><a title="知奇课堂-Python开发课程" href="#"><span class="thumbnail">
<img class="thumb" data-original="images/201610181739277776.jpg" src="images/201610181739277776.jpg"
     alt="知奇课堂-Python开发课程" style="display: block;">
</span><span class="text">知奇课堂-Python开发课程</span><span class="muted"><i class="glyphicon glyphicon-time"></i>
2016-11-01
</span><span class="muted"><i class="glyphicon glyphicon-eye-open"></i>88</span></a></li>

                </ul>
            </div>

        </aside>
    </section>


{% endblock a %}

templates/search.html
  <div class="widget widget_search">
                <form class="navbar-form" action="{% url 'blog:search' %}" method="post">
                    {% csrf_token %}
                    <div class="input-group">
                        <input type="text" name="keyword" class="form-control" size="35" placeholder="请输入关键字"
                               maxlength="15" autocomplete="off">
                        <span class="input-group-btn">
		<button class="btn btn-default btn-search" name="search" type="submit">搜索</button>
		</span></div>
                </form>
            </div>